# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1-5"

permissions:
  contents: read
  pull-requests: write
  packages: read
  id-token: write

jobs:
  nightly-build:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@DAT-20199
    with:
      nightly: true
    secrets: inherit
