name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  pull-requests: write
  packages: read
  id-token: write

jobs:
  build-test:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@main
    with:
      os: '["ubuntu-latest"]'
    secrets: inherit
